vscode:
  extensions:
    - betterthantomorrow.calva
    - mhutchie.git-graph
tasks:
  - init: |
      brew install leiningen
      wget -qO zprint https://github.com/kkinnear/zprint/releases/download/1.2.3/zprintl-1.2.3
      chmod +x zprint
      sudo mv zprint /usr/local/bin
    command: make test
ports:
  - port: 8020
    onOpen: open-browser