name: Test
on: [push]
jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          lein: 2.9.1
      - name: Run tests
        run: lein bat-test
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate main.js
        run: lein run -m shadow.cljs.devtools.cli release app
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs